name: CI/CD

on: 
  push: 
    branches: [ master ]

  workflow_dispatch:


env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: 'us-west-2'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:      
      - uses: actions/checkout@v2
      
      - name: Setup Ruby 
        uses: ruby/setup-ruby@v1  
        with: 
          ruby-version: 3.2.2
          bundler-cache: true 
      
      - name: Build Site 
        run: bundle exec jekyll build 
        env: 
          JEKYLL_ENV: production
      
      - name: Upload to S3
        run: aws s3 sync ./_site/ s3://rice-and-potato.com --delete
